import numpy as np
# (a) 
# (i)
array = np.array([[1,-2,3],[-4,5,-6]])
abs_array = np.abs(array)
print(abs_array)
# (ii)
flat = array.flatten()
q25 = np.percentile(flat,25)
q50 = np.percentile(flat,50)
q75 = np.percentile(flat,75)
print(q25)
print(q50)
print(q75)
q25_col = np.percentile(array,25,axis=0)
q50_col = np.percentile(array,50,axis=0)
q75_col = np.percentile(array,75,axis=0)
print(q25_col)
print(q50_col)
print(q75_col)
q25_row = np.percentile(array,25,axis=1)
q50_row = np.percentile(array,50,axis=1)
q75_row = np.percentile(array,75,axis=1)
print(q25_row)
print(q50_row)  
print(q75_row)
# (iii)
mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print(mean_flat)
print(median_flat)
print(std_flat)
mean_col = np.mean(array,axis=0)
median_col = np.median(array,axis=0)
std_col = np.std(array,axis=0)
print(mean_col)
print(median_col)
print(std_col)
mean_row = np.mean(array,axis=1)
median_row = np.median(array,axis=1)
std_row = np.std(array,axis=1)
print(mean_row)
print(median_row)
print(std_row)
# (b)
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
floor = np.floor(a)
ceil = np.ceil(a)
trunc = np.trunc(a)
round = np.round(a)
print(floor)
print(ceil)
print(trunc)
print(round)   